### ISSUE TITLE
this game sucks

### ISSUE THREAD

**Issue by Crimson-is-stupid** [ItsLJcool/gamejam-whiskers#1]

**Comment by Crimson-is-stupid** [comment]
Obtain Uranium-238
Boil Uranium-238 into a gas
Run Uranium-238 through cell membranes, and capture the Uranium-235 particles
Obtain 33 pounds of enriched Uranium-235
Buy 10 pounds of trinitrotoluene (TNT)
Encase trinitrotoluene in a steel box
Encase Uranium-235 in the same steel box with at least 90% concentration
Place a fuse linking the trinitrotoluene to a switch, either radio contnrolled or manually burned
Detonate the trinitrotoluene so the nuclear fission and nuclear detonation can happen

**Comment by ImagineThisGuy2** [comment]
this is very fake i love this

**Comment by ItsLJcool** [comment]
not an issue, also uranium deadly

**Comment by ImagineThisGuy2** [comment]
aw shucks

**Comment by Crimson-is-stupid** [comment]
> not an issue, also uranium deadly

you said this is not an issue when it clearly is your run shall now be ruined
